version: '3.8'

services:
  api:
    build: .
    container_name: gerente-banco-api
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance  # Persiste o banco de dados SQLite
    restart: unless-stopped